### PR TITLE
LPS-62036

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by bejondshao** [comment]
Hey @peterfellwock , cc @hhuijser 

Would you take a while to review this?

Thanks
Bejond

**Comment by bejondshao** [comment]
Hey @peterfellwock , cc @hhuijser

Would you take a while to review this?

Thanks
Bejond

**Comment by peterfellwock** [comment]
@bejondshao this looks fine. Remove that class.

**Comment by bejondshao** [comment]
Hi @peterfellwock ,

This LPS is in a little hurry. Would you send it to Brian?

Thanks
Bejond

**Comment by peterfellwock** [comment]
Pulled, could not rebase, re-did your commit on the latest master and sent to @brianchandotcom, https://github.com/brianchandotcom/liferay-portal/pull/36911

it has been merged.

**Pull request closed without merging**
