### PR TITLE
LPS-68072 Add test

### PR DESCRIPTION
**Pull request by epgarcia**
Hi @peterfellwock 

I performed some changes to your PR and added integration tests. Could you please review it?

I'm not sure about how this converter is aimed to be installed. It does not contain the .lfrbuild-portal so I assume it's not going to be available by default, right? Regarding the upgrade process, I wasn't sure about the naming. I left it as "WysiwygConverter_" but it could be renamed to "UpgradeWysiwyg_" and associated to an upgrade step, as we do in similar situations. Maybe @juliocamarero, @jorgeferrer and you made this decision for some reason.

Thanks

### CODE REVIEW

**Comment by peterfellwock** [comment]
@epgarcia I named it WysiwygConverter because its "converting" not upgrading but let me know what you think, I will make whatever change you want.

**Comment by peterfellwock** [comment]
ci:retest

**Comment by epgarcia** [comment]
ci:retest

**Comment by epgarcia** [comment]
@peterfellwock I'm fine with the naming. If you're ok with my changes please send the PR to Brian. Thanks

**Pull request closed without merging**
