### PR TITLE
LPS-59621 remove calls to *ServiceUtil in plugins-admin-web

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @hhuijser

**Comment by peterfellwock** [comment]
@juliocamarero and @hhuijser this looks great. Do you want me to pass to @brianchandotcom ?

**Comment by juliocamarero** [comment]
Hey @peterfellwock 

this is just a bunch of automatic changes that need to be carefully reviewed by someone who knows this app. Do you know to which team it belongs? I just saw you made a lot of recent changes to it...

**Comment by peterfellwock** [comment]
I just migrated it, @JorgeFerrer, do you know the owner of plugins_admin?

**Comment by JorgeFerrer** [comment]
Eventually it should be the Users Admin and Portal Configuration team, but
it's not been transitioned yet so it doesn't have a clear owner.

**Comment by hhuijser** [comment]
I'll send it to Brian

**Pull request closed without merging**
