### PR TITLE
Login Portlets OSGi - Clean

### PR DESCRIPTION
**Pull request by peterfellwock**

### CODE REVIEW

**Comment by peterfellwock** [comment]
ci:retest

**Comment by peterfellwock** [comment]
ci:retest

**Comment by peterfellwock** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
I restarted this job on 10/15/15 at 12:29pm.

**Comment by peterfellwock** [comment]
ci:retest

**Comment by peterfellwock** [comment]
ci:retest

**Comment by peterfellwock** [comment]
ci:retest

**Pull request closed without merging**
