### PR TITLE
LPS-56537 - frontend-editor-lang module

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Peter,

Attached is the editor-lang bundle.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by mjbradford89** [comment]
Hmm looks like we'll have to put a build.xml in the module too.  Or someone add an exception to that test is failing

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by peterfellwock** [comment]
Lets review together, close this, rebase and send me a new PR and I will pass to Brian

**Pull request closed without merging**
