### PR TITLE
LPS-55209 - Create an ant task in frontend-js-web that will deploy without running all dependent tasks

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Peter,

Attached is an update for https://issues.liferay.com/browse/LPS-55209.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by mjbradford89** [comment]
Closing this one. I just realized the exact same thing can be accomplished by just running ant deploy without ant clean (facepalm)

**Comment by mjbradford89** [comment]
NEVERMIND, no it cannot. because the jar task won't run if the classes dir isn't delted.

**Comment by peterfellwock** [comment]
@mjbradford89 reviewing

**Comment by peterfellwock** [comment]
@mjbradford89 sent to https://github.com/rotty3000/liferay-portal/pull/826

**Pull request closed without merging**
